# Use official Airflow 3.0.4 image
FROM apache/airflow:3.0.4

# Copy requirements.txt into the container
COPY requirements.txt .

# Switch to airflow user before installing Python packages
# Run Airflow as non-root for security and proper file permissions !! NEEDED !!
USER airflow

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt